spring:
  profiles:
    active: dev
    resources:
      static-locations:
        file: C:/file/


  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true



logging:
  level:
    cn.bptop.jckc.dao: debug




server:
  tomcat:
    uri-encoding: utf-8
